services:
  # The official FlareSolverr service
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      # Set your timezone to avoid timestamp issues in logs
      - TZ=America/New_York
    # We don't need to expose the port to the host if only other containers access it,
    # but it can be useful for direct testing.
    # ports:
    #   - "8191:8191"
    restart: unless-stopped

  # Our new proxy service that translates and forwards requests
  flaresolverr-proxy:
    # Use the latest image from the GitHub Container Registry
    image: ghcr.io/lenni0451/flaresolverr-proxy:main
    container_name: flaresolverr-proxy
    ports:
      # Expose the proxy on port 8888 on your server's IP
      - "8888:8888"
    environment:
      # This is the crucial part: it tells our script where to find FlareSolverr.
      # Docker Compose creates a network where services can be reached by their name.
      - FLARESOLVERR_URL=http://flaresolverr:8191/v1
      # You can override the default proxy port here if you change it in the 'ports' section
      - PROXY_PORT=8888
      # You can adjust the timeout if needed (in milliseconds)
      - FLARESOLVERR_TIMEOUT=120000
    depends_on:
      - flaresolverr
    restart: unless-stopped
